# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aqi_api/v1alpha1/datahub/resources/metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aqi_api/v1alpha1/datahub/resources/metadata.proto',
  package='ekko771.aqi.v1alpha1.datahub.metadata',
  syntax='proto3',
  serialized_options=_b('ZFgithub.com/ekko771/AQI-grpc-server/aqi_api/v1alpha1/resources/metadata'),
  serialized_pb=_b('\n1aqi_api/v1alpha1/datahub/resources/metadata.proto\x12%ekko771.aqi.v1alpha1.datahub.metadata\"\x86\x01\n\nObjectMeta\x12\x0e\n\x06\x43ounty\x18\x01 \x01(\t\x12\x10\n\x08Latitude\x18\x02 \x01(\t\x12\x11\n\tLongitude\x18\x03 \x01(\t\x12\x11\n\tPollutant\x18\x04 \x01(\t\x12\x0e\n\x06SiteId\x18\x05 \x01(\t\x12\x10\n\x08SiteName\x18\x06 \x01(\t\x12\x0e\n\x06Status\x18\x07 \x01(\tBHZFgithub.com/ekko771/AQI-grpc-server/aqi_api/v1alpha1/resources/metadatab\x06proto3')
)




_OBJECTMETA = _descriptor.Descriptor(
  name='ObjectMeta',
  full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='County', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.County', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.Latitude', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.Longitude', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Pollutant', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.Pollutant', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SiteId', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.SiteId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SiteName', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.SiteName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Status', full_name='ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta.Status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['ObjectMeta'] = _OBJECTMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectMeta = _reflection.GeneratedProtocolMessageType('ObjectMeta', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTMETA,
  '__module__' : 'aqi_api.v1alpha1.datahub.resources.metadata_pb2'
  # @@protoc_insertion_point(class_scope:ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta)
  })
_sym_db.RegisterMessage(ObjectMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
