# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aqi_api/v1alpha1/datahub/common/metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aqi_api/v1alpha1/datahub/common/metrics.proto',
  package='ekko771.aqi.v1alpha1.datahub.common',
  syntax='proto3',
  serialized_options=_b('Z6github.com/ekko771/api/aqi_api/v1alpha1/common/metrics'),
  serialized_pb=_b('\n-aqi_api/v1alpha1/datahub/common/metrics.proto\x12#ekko771.aqi.v1alpha1.datahub.common\"\x87\x02\n\x06Sample\x12\x0b\n\x03\x61qi\x18\x01 \x01(\t\x12\n\n\x02\x63o\x18\x02 \x01(\t\x12\x0e\n\x06\x63o_8hr\x18\x03 \x01(\t\x12\n\n\x02no\x18\x04 \x01(\t\x12\x0b\n\x03no2\x18\x05 \x01(\t\x12\x0b\n\x03nox\x18\x06 \x01(\t\x12\n\n\x02o3\x18\x07 \x01(\t\x12\x0e\n\x06o3_8hr\x18\x08 \x01(\t\x12\x0c\n\x04pm10\x18\t \x01(\t\x12\x10\n\x08pm10_avg\x18\n \x01(\t\x12\x0c\n\x04pm25\x18\x0b \x01(\t\x12\x10\n\x08pm25_avg\x18\x0c \x01(\t\x12\x0b\n\x03so2\x18\r \x01(\t\x12\x0f\n\x07so2_avg\x18\x0e \x01(\t\x12\x12\n\nwind_direc\x18\x0f \x01(\t\x12\x12\n\nwind_speed\x18\x10 \x01(\t\x12\x0c\n\x04time\x18\x11 \x01(\tB8Z6github.com/ekko771/api/aqi_api/v1alpha1/common/metricsb\x06proto3')
)




_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='ekko771.aqi.v1alpha1.datahub.common.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aqi', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.aqi', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='co', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.co', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='co_8hr', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.co_8hr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.no', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no2', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.no2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nox', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.nox', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='o3', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.o3', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='o3_8hr', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.o3_8hr', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pm10', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.pm10', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pm10_avg', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.pm10_avg', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pm25', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.pm25', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pm25_avg', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.pm25_avg', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='so2', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.so2', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='so2_avg', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.so2_avg', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_direc', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.wind_direc', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.wind_speed', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ekko771.aqi.v1alpha1.datahub.common.Sample.time', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=350,
)

DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'aqi_api.v1alpha1.datahub.common.metrics_pb2'
  # @@protoc_insertion_point(class_scope:ekko771.aqi.v1alpha1.datahub.common.Sample)
  })
_sym_db.RegisterMessage(Sample)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
