# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aqi_api/v1alpha1/datahub/metrics/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aqi_api.v1alpha1.datahub.metrics import metrics_pb2 as aqi__api_dot_v1alpha1_dot_datahub_dot_metrics_dot_metrics__pb2
from aqi_api.v1alpha1.datahub.resources import metadata_pb2 as aqi__api_dot_v1alpha1_dot_datahub_dot_resources_dot_metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aqi_api/v1alpha1/datahub/metrics/service.proto',
  package='ekko771.aqi.v1alpha1.datahub.metrics',
  syntax='proto3',
  serialized_options=_b('ZCgithub.com/ekko771/AQI-grpc-server/aqi_api/v1alpha1/datahub/metrics'),
  serialized_pb=_b('\n.aqi_api/v1alpha1/datahub/metrics/service.proto\x12$ekko771.aqi.v1alpha1.datahub.metrics\x1a.aqi_api/v1alpha1/datahub/metrics/metrics.proto\x1a\x31\x61qi_api/v1alpha1/datahub/resources/metadata.proto\"[\n\x14ListAQIMetricRequest\x12\x43\n\x08metadata\x18\x01 \x03(\x0b\x32\x31.ekko771.aqi.v1alpha1.datahub.metadata.ObjectMeta\"]\n\x15ListAQIMetricResponse\x12\x44\n\x0b\x61qi_metrics\x18\x01 \x03(\x0b\x32/.ekko771.aqi.v1alpha1.datahub.metrics.AQIMetricBEZCgithub.com/ekko771/AQI-grpc-server/aqi_api/v1alpha1/datahub/metricsb\x06proto3')
  ,
  dependencies=[aqi__api_dot_v1alpha1_dot_datahub_dot_metrics_dot_metrics__pb2.DESCRIPTOR,aqi__api_dot_v1alpha1_dot_datahub_dot_resources_dot_metadata__pb2.DESCRIPTOR,])




_LISTAQIMETRICREQUEST = _descriptor.Descriptor(
  name='ListAQIMetricRequest',
  full_name='ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricRequest.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=278,
)


_LISTAQIMETRICRESPONSE = _descriptor.Descriptor(
  name='ListAQIMetricResponse',
  full_name='ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aqi_metrics', full_name='ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricResponse.aqi_metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=373,
)

_LISTAQIMETRICREQUEST.fields_by_name['metadata'].message_type = aqi__api_dot_v1alpha1_dot_datahub_dot_resources_dot_metadata__pb2._OBJECTMETA
_LISTAQIMETRICRESPONSE.fields_by_name['aqi_metrics'].message_type = aqi__api_dot_v1alpha1_dot_datahub_dot_metrics_dot_metrics__pb2._AQIMETRIC
DESCRIPTOR.message_types_by_name['ListAQIMetricRequest'] = _LISTAQIMETRICREQUEST
DESCRIPTOR.message_types_by_name['ListAQIMetricResponse'] = _LISTAQIMETRICRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListAQIMetricRequest = _reflection.GeneratedProtocolMessageType('ListAQIMetricRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTAQIMETRICREQUEST,
  '__module__' : 'aqi_api.v1alpha1.datahub.metrics.service_pb2'
  # @@protoc_insertion_point(class_scope:ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricRequest)
  })
_sym_db.RegisterMessage(ListAQIMetricRequest)

ListAQIMetricResponse = _reflection.GeneratedProtocolMessageType('ListAQIMetricResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTAQIMETRICRESPONSE,
  '__module__' : 'aqi_api.v1alpha1.datahub.metrics.service_pb2'
  # @@protoc_insertion_point(class_scope:ekko771.aqi.v1alpha1.datahub.metrics.ListAQIMetricResponse)
  })
_sym_db.RegisterMessage(ListAQIMetricResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
